/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logicasjava.Biblioteca;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Waselkin
 */
public class GUI_Devolucao_Emprestimo extends javax.swing.JFrame {
    
    Vector<String> vectorNomesUsuarios = new Vector<>();

    /**
     * Creates new form GUI_Devolucao_Emprestimo
     */
    public GUI_Devolucao_Emprestimo() {
        initComponents();
        //CHAMADA DAS FUNÇÕES
        mostraUsuarios(); 
        mostraLivros();
        //PARAMENTROS DA TELA
        setResizable(false);
        setSize(700, 500);
        setLocationRelativeTo(this);
    }

    private void mostraUsuarios(){
        cbNomeDevolucao.removeAllItems(); // REMOVE OS ITENS DA COMBOBOX PARA QUE NÃO TENHA DUPLICIDADE AO CLICAR NELA
        cbNomeEmprestimo.removeAllItems();
        cbNomeEmprestimo.addItem(null); // INICIA A COMBOBOX COMO VAZIA
        cbNomeDevolucao.addItem(null);
        cbNomeDevolucao.setSelectedIndex(0);
        cbNomeEmprestimo.setSelectedIndex(0);
        
        
        for ( Usuario u : Usuario.listarUsuarios() ){
            
            cbNomeEmprestimo.addItem(u);
            
            // SE O USUÁRIO TIVER MAIS DE UM LIVRO ELE É ADICIONADO A LISTA DE DEVOLUÇÃO
            if ( u.getQtdLivrosEmprestados() > 0 ) {
                cbNomeDevolucao.addItem(u);
            }
        }
    }
    
    private void mostraLivros(){
        cbLivroDevolucao.removeAllItems(); // REMOVE OS ITENS DA COMBOBOX PARA QUE NÃO TENHA DUPLICIDADE AO CLICAR NELA
        cbLivroEmprestimo.removeAllItems();
        cbLivroEmprestimo.addItem(null); // INICIA A COMBOBOX COMO VAZIA
        cbLivroDevolucao.addItem(null);
        cbLivroDevolucao.setSelectedIndex(0);
        cbLivroEmprestimo.setSelectedIndex(0);
        
        for( Livro l : Livro.mostraLivros() ){
            // SE O LIVRO NÃO ESTIVER DISPONIVEL, ADD ELE A SELEÇÃO DE DEVOLUCAO
            if ( l.getDisponivel() == false ){
                cbLivroDevolucao.addItem(l);
            }
            // SE O LIVRO ESTIVER DISPONIVEL, ADD ELE A SELEÇÃO DE EMPRESTIMO
            if( l.getDisponivel() ) {
                cbLivroEmprestimo.addItem(l);
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEmprestar = new javax.swing.JButton();
        cbNomeEmprestimo = new javax.swing.JComboBox<>();
        cbLivroEmprestimo = new javax.swing.JComboBox<>();
        btnConsularEmprestimo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDevolver = new javax.swing.JButton();
        cbLivroDevolucao = new javax.swing.JComboBox<>();
        cbNomeDevolucao = new javax.swing.JComboBox<>();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Empréstimo");

        jLabel3.setText("Nome");

        jLabel4.setText("Livro");

        btnEmprestar.setText("EMPRESTAR");
        btnEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestarActionPerformed(evt);
            }
        });

        cbNomeEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeEmprestimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEmprestar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNomeEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLivroEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNomeEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbLivroEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEmprestar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConsularEmprestimo.setText("CONSULTAR EMPRÉSTIMOS");
        btnConsularEmprestimo.setToolTipText("");
        btnConsularEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsularEmprestimoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Devolução");

        jLabel5.setText("Nome");

        jLabel6.setText("Livro");

        btnDevolver.setText("DEVOLVER");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDevolver)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cbLivroDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbNomeDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNomeDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLivroDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnDevolver)
                .addGap(60, 60, 60))
        );

        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsularEmprestimo)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsularEmprestimo)
                    .addComponent(btnHome))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestarActionPerformed
        // TODO add your handling code here:
        Livro livroSelecionado = (Livro) cbLivroEmprestimo.getSelectedItem(); //PEGA O DADO DA COMBOBOX
        Usuario usuarioSelecionado = (Usuario) cbNomeEmprestimo.getSelectedItem(); //PEGA O DADO DA COMBOBOX
        
        if ( cbNomeEmprestimo.getSelectedItem() == null && cbLivroEmprestimo.getSelectedItem() == null ){
                javax.swing.JOptionPane.showMessageDialog(this, "TODOS OS CAMPOS DEVEM SER SELECIONADOS!");
        } else{
                if ( usuarioSelecionado.getQtdLivrosEmprestados() >= 5 ) {
                    javax.swing.JOptionPane.showMessageDialog(this, "LIMITE DE EMPRÉSTIMO ATINGIDO!!");
                } else{
                        // SE O LIVRO ESTIVER DISPONIVEL ENTRA NA CONDIÇÃO
                        if ( livroSelecionado.getDisponivel()) {
                        livroSelecionado.emprestar();
                        usuarioSelecionado.adicionarLivro(livroSelecionado); //ADICIONA O LIVRO SELECIONADO A LISTA DE LIVROS QUE O USUARIO POSSUI
                        cbLivroEmprestimo.removeItem(livroSelecionado); //REMOVE O ITEM DA SELEÇÃO DE EMPRESTIMO
                        cbLivroDevolucao.addItem(livroSelecionado); // ADD A SELEÇÃO DE DEVOLUÇÃO
                        cbNomeDevolucao.removeAllItems();
                        cbNomeDevolucao.addItem(usuarioSelecionado); // ADD O USUARIO A SELEÇÃO DE DEVOLUÇÃO
                        cbNomeDevolucao.setSelectedIndex(0);
                        javax.swing.JOptionPane.showMessageDialog(this, "LIVRO EMPRESTADO!");
                        cbLivroEmprestimo.setSelectedIndex(0);
                        cbNomeEmprestimo.setSelectedIndex(0);
                    }
                }  
            }
    }//GEN-LAST:event_btnEmprestarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // TODO add your handling code here:
        Livro livroSelecionado = (Livro) cbLivroDevolucao.getSelectedItem(); //PEGA O DADO DA COMBOBOX
        Usuario usuarioSelecionado = (Usuario) cbNomeDevolucao.getSelectedItem(); //PEGA O DADO DA COMBOBOX
        
        if ( cbLivroDevolucao.getSelectedItem() == null || cbNomeDevolucao.getSelectedItem() == null ){
            javax.swing.JOptionPane.showMessageDialog(this, "TODOS OS CAMPOS DEVEM SER SELECIONADOS!");
        } else {
                    // SE O LIVRO NÃO ESTIVER DISPONIVEL ENTRA NA CONDIÇÃO
                if ( livroSelecionado.getDisponivel() == false ) {
                    livroSelecionado.devolver();
                    usuarioSelecionado.getLivrosEmprestados().remove(livroSelecionado);
                    cbLivroDevolucao.removeItem(livroSelecionado); //REMOVE O ITEM DA SELEÇÃO DE DEVOLUÇÃO
                    cbLivroDevolucao.setSelectedIndex(0);
                    cbLivroEmprestimo.addItem(livroSelecionado); // ADD A SELEÇÃO DE DISPONIVEL
                    javax.swing.JOptionPane.showMessageDialog(this, "LIVRO DEVOLVIDO!");
                    cbNomeDevolucao.setSelectedIndex(0);
                    int qtdEmprestada = usuarioSelecionado.getQtdLivrosEmprestados() - 1;
                    usuarioSelecionado.setQtdLivrosEmprestados(qtdEmprestada);
                    

                    if ( usuarioSelecionado.getLivrosEmprestados().isEmpty() ) {
                        cbNomeDevolucao.removeItem(usuarioSelecionado); //REMOVE O USARIO DA SELEÇÃO DE USUARIOS COM LIVROS A EMPRESTAR
                    }

                    Collections.sort(Livro.mostraLivros()); //ORDENA A LISTA POR ORDEM ALFABETICA
                    cbLivroDevolucao.setSelectedIndex(0);
                }
            }
        
        

    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        //VOLTA PARA A HOME
        GUI_Home gh = new GUI_Home();
        gh.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void cbNomeEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNomeEmprestimoActionPerformed

    private void btnConsularEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsularEmprestimoActionPerformed
        // TODO add your handling code here:
        GUI_Consulta gc = new GUI_Consulta();
        gc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConsularEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Devolucao_Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Devolucao_Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Devolucao_Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Devolucao_Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Devolucao_Emprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsularEmprestimo;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnEmprestar;
    private javax.swing.JButton btnHome;
    private javax.swing.JComboBox<Livro> cbLivroDevolucao;
    private javax.swing.JComboBox<Livro> cbLivroEmprestimo;
    private javax.swing.JComboBox<Usuario> cbNomeDevolucao;
    private javax.swing.JComboBox<Usuario> cbNomeEmprestimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
